### PR TITLE
add: minimum node version required to readme.md

### PR DESCRIPTION
**Pull request by themujahidkhan**
Added about **Minimum node version required** to readme.md file

### CODE REVIEW

**Review by suuunly — DISMISSED** [review]
Lgtm! 😁

**Comment by suuunly** [comment]
The linter failed due to incorrect import order :)

Failed to compile.
17:07:14.462 |  
17:07:14.462 | ./src/database/index.ts
17:07:14.462 | 1:1  Error: Run autofix to sort these imports!  simple-import-sort/imports
17:07:14.462 |  
17:07:14.462 | info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
17:07:14.481 | error Command failed with exit code 1.
17:07:14.481 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:07:14.500 | Error: Command "yarn run build" exited with 1
17:07:15.170

If you correct that, then we can merge it in 😄

**Comment by themujahidkhan** [comment]
> The linter failed due to incorrect import order :)
> 
> Failed to compile. 17:07:14.462 |   17:07:14.462 | ./src/database/index.ts 17:07:14.462 | 1:1 Error: Run autofix to sort these imports! simple-import-sort/imports 17:07:14.462 |   17:07:14.462 | info - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules 17:07:14.481 | error Command failed with exit code 1. 17:07:14.481 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 17:07:14.500 | Error: Command "yarn run build" exited with 1 17:07:15.170
> 
> If you correct that, then we can merge it in 😄

I've corrected the code as requested; It was an auto-format code editor issue.

**Review by themujahidkhan — COMMENTED** [review]
I've imported files as intended to avoid conflicts in loading the modules & scripts. Let me know if any changes are required.

**Review by suuunly — APPROVED** [review]

**Comment by suuunly** [comment]
Nice. It has been merged 😁😁

**Pull request merged**
